# Required to make the "experiments" dir the default one for the output of the models
hydra:
  job:
    chdir: true
  run:
    dir: ./experiments/${train.model}/${now:%Y-%m-%d}/${now:%H-%M-%S}

# Default config for train and data
defaults:
  - _self_
  - train: tiny_vgg
  - dataset: pizza_steak_sushi

project: 'visiope'